#!/bin/bash

ANY_FAILED=0

swift --version

swift build -c release --target BSONSchema ||
    ANY_FAILED=1

swift run   -c release          BSONTests ||
    ANY_FAILED=1

swift run   -c release          BSONDecodingTests ||
    ANY_FAILED=1

swift run   -c release          BSONEncodingTests ||
    ANY_FAILED=1


swift build -c release --target Heartbeats ||
    ANY_FAILED=1

swift run   -c release          HeartbeatsTests ||
    ANY_FAILED=1


swift build -c release --target MongoDriver ||
    ANY_FAILED=1

swift run   -c release          MongoDriverTests ||
    ANY_FAILED=1


swift build -c release --target MongoDB ||
    ANY_FAILED=1

swift run   -c release          MongoDBTests ||
    ANY_FAILED=1

swift build -c release --target MongoDSLAPITests ||
    ANY_FAILED=1

if [ "$ANY_FAILED" -ne 0 ] ; then
    exit
fi
