#!/bin/bash

swift --version
swift build -c release --target BSONSchema
swift run   -c release          BSONTests
swift run   -c release          BSONDecodingTests
swift run   -c release          BSONEncodingTests

swift build -c release --target Heartbeats
swift run   -c release          HeartbeatsTests

swift build -c release --target MongoSessions
swift run   -c release          MongoSessionsTests

swift build -c release --target MongoDB
swift run   -c release          MongoDBTests
