version: "3.9"
services:
    # a mock standalone deployment
    mongo-single:
        image: mongo:latest
        hostname: mongo-single
        networks:
            - mongonet
        ports:
            - 40000:27017
        restart: always
        volumes:
            - ./create-users.js:/docker-entrypoint-initdb.d/create-users.js
            - ./mongod.conf:/etc/mongod.conf
            - ./data/db:/data/db
        command: mongod --config /etc/mongod.conf

    mongo-0:
        image: mongo:latest
        hostname: mongo-0
        networks:
            - mongonet
        ports:
            - 30000:27017
        restart: always
        volumes:
            # cannot put this in docker-entrypoint-initdb.d, it does not work
            - ./create-replica-set.js:/create-replica-set.js
            - ./test-set.conf:/etc/mongod.conf
            - ./data-0/db:/data/db
        command: mongod --config /etc/mongod.conf
        deploy:
            resources:
                limits:
                    cpus: '1.00'
                    memory: 500M
    mongo-1:
        image: mongo:latest
        hostname: mongo-1
        networks:
            - mongonet
        ports:
            - 30001:27017
        restart: always
        volumes:
            - ./test-set.conf:/etc/mongod.conf
            - ./data-1/db:/data/db
        command: mongod --config /etc/mongod.conf
        deploy:
            resources:
                limits:
                    cpus: '1.00'
                    memory: 500M
    mongo-2:
        image: mongo:latest
        hostname: mongo-2
        networks:
            - mongonet
        ports:
            - 30002:27017
        restart: always
        volumes:
            - ./test-set.conf:/etc/mongod.conf
            - ./data-2/db:/data/db
        command: mongod --config /etc/mongod.conf
        deploy:
            resources:
                limits:
                    cpus: '1.00'
                    memory: 500M
    mongo-3:
        image: mongo:latest
        hostname: mongo-3
        networks:
            - mongonet
        ports:
            - 30003:27017
        restart: always
        volumes:
            - ./test-set.conf:/etc/mongod.conf
            - ./data-3/db:/data/db
        command: mongod --config /etc/mongod.conf
        deploy:
            resources:
                limits:
                    cpus: '1.00'
                    memory: 500M
    mongo-4:
        image: mongo:latest
        hostname: mongo-4
        networks:
            - mongonet
        ports:
            - 30004:27017
        restart: always
        volumes:
            - ./test-set.conf:/etc/mongod.conf
            - ./data-4/db:/data/db
        command: mongod --config /etc/mongod.conf
        deploy:
            resources:
                limits:
                    cpus: '1.00'
                    memory: 500M
    mongo-5:
        image: mongo:latest
        hostname: mongo-5
        networks:
            - mongonet
        ports:
            - 30005:27017
        restart: always
        volumes:
            - ./test-set.conf:/etc/mongod.conf
            - ./data-5/db:/data/db
        command: mongod --config /etc/mongod.conf
        deploy:
            resources:
                limits:
                    cpus: '1.00'
                    memory: 500M
    mongo-6:
        image: mongo:latest
        hostname: mongo-6
        networks:
            - mongonet
        ports:
            - 30006:27017
        restart: always
        volumes:
            - ./test-set.conf:/etc/mongod.conf
            - ./data-6/db:/data/db
        command: mongod --config /etc/mongod.conf
        deploy:
            resources:
                limits:
                    cpus: '1.00'
                    memory: 500M

networks: 
    mongonet:
        name: mongonet
