#!/bin/bash
set -e
swift --version

# Note: these tests generally fail in debug mode because it takes a long time to
# complete cryptographic authentication, and the driver will time out before it
# completes.
swift build -c release \
    --explicit-target-dependency-import-check=error \
    --build-tests

swift test -c release \
    --skip-build \
    --no-parallel \
    --explicit-target-dependency-import-check=error

for f in .build/release/*Tests; do
    $f
done
