#!/bin/bash
set -e
swift --version
swift test -c release --explicit-target-dependency-import-check=error
swift build -c release --explicit-target-dependency-import-check=error
for f in .build/release/*Tests; do
  $f
done
