name: test

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    linux:
        runs-on: ubuntu-24.04
        name: Amazon Linux 2023

        strategy:
            matrix:
                image:
                -   tayloraswift/5.10.0-amazonlinux2023:latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Set up mock deployments
                run: |
                    docker compose -f .github/mongonet/docker-compose.yml up -d

            -   name: Initialize replica set
                run: |
                    timeout 60s bash -c \
                    'until docker exec -t mongonet-mongo-0-1 /bin/mongosh --file /create-replica-set.js; do sleep 1; done'

            -   name: Run pipeline
                run: |
                    docker run -t --rm --network=mongonet \
                        --name mongonet-environment \
                        --user root \
                        -v $PWD:/swift-mongodb \
                        -w /swift-mongodb \
                        ${{ matrix.image }} \
                        /bin/bash $(echo .github/pipeline)

